// OHLCV candle data
export interface Candle {
  time: number; // Unix timestamp
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

// Futures contract config
export interface ContractConfig {
  symbol: string;
  name: string;
  pointValue: number;
  tickSize: number;
}

export const CONTRACTS: Record<string, ContractConfig> = {
  "NQ=F": { symbol: "NQ=F", name: "NQ (Nasdaq 100)", pointValue: 20, tickSize: 0.25 },
  "MNQ=F": { symbol: "MNQ=F", name: "MNQ (Micro Nasdaq)", pointValue: 2, tickSize: 0.25 },
  "ES=F": { symbol: "ES=F", name: "ES (S&P 500)", pointValue: 50, tickSize: 0.25 },
  "GC=F": { symbol: "GC=F", name: "GC (Gold)", pointValue: 100, tickSize: 0.10 },
  "CL=F": { symbol: "CL=F", name: "CL (Crude Oil)", pointValue: 1000, tickSize: 0.01 },
};

// Trade record from backtest
export interface Trade {
  id: number;
  instrument: string;
  side: "long" | "short";
  size: number;
  entryPrice: number;
  exitPrice: number;
  entryTime: number;
  exitTime: number;
  stopLoss: number | null;
  takeProfit: number | null;
  pnl: number;
  pnlPoints: number;
  commission: number;
}

// Backtest result metrics
export interface BacktestMetrics {
  totalTrades: number;
  winRate: number;
  lossRate: number;
  totalReturn: number;
  totalReturnPct: number;
  maxDrawdown: number;
  maxDrawdownPct: number;
  maxConsecutiveLosses: number;
  maxConsecutiveWins: number;
  profitFactor: number;
  sharpeRatio: number;
  avgWin: number;
  avgLoss: number;
}

// Full backtest result
export interface BacktestResult {
  trades: Trade[];
  equityCurve: { time: number; value: number }[];
  metrics: BacktestMetrics;
  strategyName: string;
  strategyDescription: string;
}

// Strategy generated by AI
export interface GeneratedStrategy {
  code: string;
  name: string;
  description: string;
  parameters: Record<string, number | string>;
}

// PineScript result from AI generation
export interface PineScriptResult {
  name: string;
  description: string;
  parameters: Record<string, string>;
  code: string;
  script_type: "strategy" | "indicator";
}

// Chat message
export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: number;
  strategyResult?: BacktestResult;
  pinescriptResult?: PineScriptResult;
}

// Tick data from Databento
export interface Tick {
  time: number; // Unix timestamp (seconds, float)
  price: number;
  size: number;
  side: string;
}

// Replay state
export interface ReplayState {
  isPlaying: boolean;
  currentBarIndex: number;
  totalBars: number;
  speed: number;
  progress: number;
  tickMode: boolean; // true = tick-by-tick replay within bars
  currentTickIndex: number;
  totalTicks: number;
}

// API request/response types
export interface ChatRequest {
  message: string;
  symbol: string;
  timeframe: string;
  conversationHistory: { role: string; content: string }[];
}

export interface ChatResponse {
  message: string;
  strategy?: GeneratedStrategy;
  backtestResult?: BacktestResult;
  pinescript?: PineScriptResult;
}

export interface DataRequest {
  symbol: string;
  period: string;
  interval: string;
}

// ─── Simulated Trading Engine Types ───

export interface Position {
  id: string;
  symbol: string;
  side: "long" | "short";
  size: number;
  entryPrice: number;
  entryTime: number;
  stopLoss: number | null;
  takeProfit: number | null;
  commission: number;
  unrealizedPnl: number;
}

export interface Order {
  id: string;
  symbol: string;
  side: "long" | "short";
  size: number;
  type: "market" | "limit" | "stop";
  price: number | null;
  status: "pending" | "filled" | "cancelled";
  createdAt: number;
}

export interface ClosedTrade {
  id: string;
  symbol: string;
  side: "long" | "short";
  size: number;
  entryPrice: number;
  exitPrice: number;
  entryTime: number;
  exitTime: number;
  stopLoss: number | null;
  takeProfit: number | null;
  pnl: number;
  pnlPoints: number;
  commission: number;
}

export interface AccountState {
  balance: number;
  equity: number;
  unrealizedPnl: number;
  positions: Position[];
  orders: Order[];
  tradeHistory: ClosedTrade[];
}

export interface RiskSettings {
  maxOpenPositions: number | null;
  allowedSymbols: string[];
  requireSlTp: boolean;
  maxLossPerTradePct: number | null;
  presetSlPct: number | null;
  presetTpPct: number | null;
}

export interface AppSettings {
  oneClickTrading: boolean;
  tradeExecutionSound: boolean;
  showNotifications: boolean;
  notificationDuration: number;
  showTradeHistoryOnChart: boolean;
  bigLotThreshold: number;
  showBuySellButtons: boolean;
  showPositionsOnChart: boolean;
  reversePositionButton: boolean;
  showPnlOnChart: boolean;
}
