// Comprehensive symbol library for SymbolsSearch
// Organized by category for quick filtering

export interface SymbolEntry {
  symbol: string;
  name: string;
  category: "stocks" | "crypto" | "futures" | "etfs" | "forex" | "nse";
}

export const SYMBOL_LIBRARY: SymbolEntry[] = [
  // ─── US Stocks (Top 80) ───
  { symbol: "AAPL", name: "Apple Inc.", category: "stocks" },
  { symbol: "MSFT", name: "Microsoft Corp.", category: "stocks" },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)", category: "stocks" },
  { symbol: "AMZN", name: "Amazon.com Inc.", category: "stocks" },
  { symbol: "NVDA", name: "NVIDIA Corp.", category: "stocks" },
  { symbol: "META", name: "Meta Platforms Inc.", category: "stocks" },
  { symbol: "TSLA", name: "Tesla Inc.", category: "stocks" },
  { symbol: "BRK-B", name: "Berkshire Hathaway B", category: "stocks" },
  { symbol: "AVGO", name: "Broadcom Inc.", category: "stocks" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", category: "stocks" },
  { symbol: "LLY", name: "Eli Lilly & Co.", category: "stocks" },
  { symbol: "V", name: "Visa Inc.", category: "stocks" },
  { symbol: "UNH", name: "UnitedHealth Group", category: "stocks" },
  { symbol: "XOM", name: "Exxon Mobil Corp.", category: "stocks" },
  { symbol: "MA", name: "Mastercard Inc.", category: "stocks" },
  { symbol: "COST", name: "Costco Wholesale", category: "stocks" },
  { symbol: "HD", name: "Home Depot Inc.", category: "stocks" },
  { symbol: "PG", name: "Procter & Gamble", category: "stocks" },
  { symbol: "JNJ", name: "Johnson & Johnson", category: "stocks" },
  { symbol: "ABBV", name: "AbbVie Inc.", category: "stocks" },
  { symbol: "WMT", name: "Walmart Inc.", category: "stocks" },
  { symbol: "NFLX", name: "Netflix Inc.", category: "stocks" },
  { symbol: "BAC", name: "Bank of America", category: "stocks" },
  { symbol: "CRM", name: "Salesforce Inc.", category: "stocks" },
  { symbol: "AMD", name: "Advanced Micro Devices", category: "stocks" },
  { symbol: "CVX", name: "Chevron Corp.", category: "stocks" },
  { symbol: "MRK", name: "Merck & Co.", category: "stocks" },
  { symbol: "KO", name: "Coca-Cola Co.", category: "stocks" },
  { symbol: "PEP", name: "PepsiCo Inc.", category: "stocks" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", category: "stocks" },
  { symbol: "ADBE", name: "Adobe Inc.", category: "stocks" },
  { symbol: "CSCO", name: "Cisco Systems", category: "stocks" },
  { symbol: "ACN", name: "Accenture PLC", category: "stocks" },
  { symbol: "DIS", name: "Walt Disney Co.", category: "stocks" },
  { symbol: "MCD", name: "McDonald's Corp.", category: "stocks" },
  { symbol: "ABT", name: "Abbott Laboratories", category: "stocks" },
  { symbol: "DHR", name: "Danaher Corp.", category: "stocks" },
  { symbol: "INTC", name: "Intel Corp.", category: "stocks" },
  { symbol: "VZ", name: "Verizon Communications", category: "stocks" },
  { symbol: "PM", name: "Philip Morris Intl.", category: "stocks" },
  { symbol: "CMCSA", name: "Comcast Corp.", category: "stocks" },
  { symbol: "NKE", name: "Nike Inc.", category: "stocks" },
  { symbol: "T", name: "AT&T Inc.", category: "stocks" },
  { symbol: "IBM", name: "IBM Corp.", category: "stocks" },
  { symbol: "ORCL", name: "Oracle Corp.", category: "stocks" },
  { symbol: "GE", name: "GE Aerospace", category: "stocks" },
  { symbol: "UNP", name: "Union Pacific", category: "stocks" },
  { symbol: "RTX", name: "RTX Corp.", category: "stocks" },
  { symbol: "CAT", name: "Caterpillar Inc.", category: "stocks" },
  { symbol: "GS", name: "Goldman Sachs", category: "stocks" },
  { symbol: "BA", name: "Boeing Co.", category: "stocks" },
  { symbol: "UBER", name: "Uber Technologies", category: "stocks" },
  { symbol: "NOW", name: "ServiceNow Inc.", category: "stocks" },
  { symbol: "ISRG", name: "Intuitive Surgical", category: "stocks" },
  { symbol: "SPGI", name: "S&P Global", category: "stocks" },
  { symbol: "INTU", name: "Intuit Inc.", category: "stocks" },
  { symbol: "BLK", name: "BlackRock Inc.", category: "stocks" },
  { symbol: "SYK", name: "Stryker Corp.", category: "stocks" },
  { symbol: "AMAT", name: "Applied Materials", category: "stocks" },
  { symbol: "ADP", name: "Automatic Data Processing", category: "stocks" },
  { symbol: "BKNG", name: "Booking Holdings", category: "stocks" },
  { symbol: "MDLZ", name: "Mondelez International", category: "stocks" },
  { symbol: "GILD", name: "Gilead Sciences", category: "stocks" },
  { symbol: "MMC", name: "Marsh & McLennan", category: "stocks" },
  { symbol: "AMT", name: "American Tower", category: "stocks" },
  { symbol: "LRCX", name: "Lam Research", category: "stocks" },
  { symbol: "TJX", name: "TJX Companies", category: "stocks" },
  { symbol: "PYPL", name: "PayPal Holdings", category: "stocks" },
  { symbol: "SQ", name: "Block Inc.", category: "stocks" },
  { symbol: "SHOP", name: "Shopify Inc.", category: "stocks" },
  { symbol: "PLTR", name: "Palantir Technologies", category: "stocks" },
  { symbol: "COIN", name: "Coinbase Global", category: "stocks" },
  { symbol: "SNAP", name: "Snap Inc.", category: "stocks" },
  { symbol: "ROKU", name: "Roku Inc.", category: "stocks" },
  { symbol: "SOFI", name: "SoFi Technologies", category: "stocks" },
  { symbol: "RIVN", name: "Rivian Automotive", category: "stocks" },
  { symbol: "LCID", name: "Lucid Group", category: "stocks" },
  { symbol: "GME", name: "GameStop Corp.", category: "stocks" },
  { symbol: "AMC", name: "AMC Entertainment", category: "stocks" },
  { symbol: "HOOD", name: "Robinhood Markets", category: "stocks" },

  // ─── African stocks (Yahoo Finance format: .JO=JSE, .NG=NGX, .NL=NSE Kenya) ───
  { symbol: "NPN.JO", name: "Naspers (JSE)", category: "stocks" },
  { symbol: "MTN.JO", name: "MTN Group (JSE)", category: "stocks" },
  { symbol: "SAB.JO", name: "SABMiller (JSE)", category: "stocks" },
  { symbol: "BID.JO", name: "Bidvest (JSE)", category: "stocks" },
  { symbol: "DANGCEM.NG", name: "Dangote Cement (NGX)", category: "stocks" },
  { symbol: "MTNN.NG", name: "MTN Nigeria (NGX)", category: "stocks" },
  { symbol: "EABL.NR", name: "East African Breweries (NSE)", category: "stocks" },
  { symbol: "KCB.NR", name: "KCB Group (NSE)", category: "stocks" },
  { symbol: "EQTY.NR", name: "Equity Group (NSE)", category: "stocks" },
  { symbol: "EEM", name: "iShares Emerging Markets", category: "etfs" },
  { symbol: "AFK", name: "VanEck Africa Index", category: "etfs" },

  // ─── Crypto (Yahoo Finance format) ───
  { symbol: "BTC-USD", name: "Bitcoin", category: "crypto" },
  { symbol: "ETH-USD", name: "Ethereum", category: "crypto" },
  { symbol: "BNB-USD", name: "Binance Coin", category: "crypto" },
  { symbol: "SOL-USD", name: "Solana", category: "crypto" },
  { symbol: "XRP-USD", name: "XRP (Ripple)", category: "crypto" },
  { symbol: "ADA-USD", name: "Cardano", category: "crypto" },
  { symbol: "DOGE-USD", name: "Dogecoin", category: "crypto" },
  { symbol: "AVAX-USD", name: "Avalanche", category: "crypto" },
  { symbol: "DOT-USD", name: "Polkadot", category: "crypto" },
  { symbol: "MATIC-USD", name: "Polygon (MATIC)", category: "crypto" },
  { symbol: "LINK-USD", name: "Chainlink", category: "crypto" },
  { symbol: "SHIB-USD", name: "Shiba Inu", category: "crypto" },
  { symbol: "LTC-USD", name: "Litecoin", category: "crypto" },
  { symbol: "UNI7083-USD", name: "Uniswap", category: "crypto" },
  { symbol: "ATOM-USD", name: "Cosmos", category: "crypto" },
  { symbol: "APE-USD", name: "ApeCoin", category: "crypto" },
  { symbol: "NEAR-USD", name: "NEAR Protocol", category: "crypto" },
  { symbol: "FTM-USD", name: "Fantom", category: "crypto" },
  { symbol: "ALGO-USD", name: "Algorand", category: "crypto" },
  { symbol: "ARB11841-USD", name: "Arbitrum", category: "crypto" },

  // ─── Futures (Yahoo Finance format) ───
  { symbol: "NQ=F", name: "NQ (Nasdaq 100 Futures)", category: "futures" },
  { symbol: "MNQ=F", name: "MNQ (Micro Nasdaq)", category: "futures" },
  { symbol: "ES=F", name: "ES (S&P 500 Futures)", category: "futures" },
  { symbol: "MES=F", name: "MES (Micro S&P 500)", category: "futures" },
  { symbol: "YM=F", name: "YM (Dow Jones Futures)", category: "futures" },
  { symbol: "RTY=F", name: "RTY (Russell 2000 Futures)", category: "futures" },
  { symbol: "GC=F", name: "GC (Gold Futures)", category: "futures" },
  { symbol: "SI=F", name: "SI (Silver Futures)", category: "futures" },
  { symbol: "CL=F", name: "CL (Crude Oil Futures)", category: "futures" },
  { symbol: "NG=F", name: "NG (Natural Gas Futures)", category: "futures" },
  { symbol: "ZB=F", name: "ZB (30-Year Bond Futures)", category: "futures" },
  { symbol: "ZN=F", name: "ZN (10-Year Note Futures)", category: "futures" },
  { symbol: "6E=F", name: "6E (Euro Futures)", category: "futures" },
  { symbol: "6J=F", name: "6J (Japanese Yen Futures)", category: "futures" },
  { symbol: "6B=F", name: "6B (British Pound Futures)", category: "futures" },
  { symbol: "HG=F", name: "HG (Copper Futures)", category: "futures" },
  { symbol: "PL=F", name: "PL (Platinum Futures)", category: "futures" },
  { symbol: "ZC=F", name: "ZC (Corn Futures)", category: "futures" },
  { symbol: "ZW=F", name: "ZW (Wheat Futures)", category: "futures" },
  { symbol: "ZS=F", name: "ZS (Soybean Futures)", category: "futures" },

  // ─── ETFs ───
  { symbol: "SPY", name: "SPDR S&P 500 ETF", category: "etfs" },
  { symbol: "QQQ", name: "Invesco QQQ (Nasdaq 100)", category: "etfs" },
  { symbol: "IWM", name: "iShares Russell 2000", category: "etfs" },
  { symbol: "DIA", name: "SPDR Dow Jones ETF", category: "etfs" },
  { symbol: "VTI", name: "Vanguard Total Market", category: "etfs" },
  { symbol: "VOO", name: "Vanguard S&P 500", category: "etfs" },
  { symbol: "VXX", name: "Barclays VIX ETN", category: "etfs" },
  { symbol: "ARKK", name: "ARK Innovation ETF", category: "etfs" },
  { symbol: "XLF", name: "Financial Select Sector", category: "etfs" },
  { symbol: "XLE", name: "Energy Select Sector", category: "etfs" },
  { symbol: "XLK", name: "Technology Select Sector", category: "etfs" },
  { symbol: "XLV", name: "Health Care Select Sector", category: "etfs" },
  { symbol: "GLD", name: "SPDR Gold Trust", category: "etfs" },
  { symbol: "SLV", name: "iShares Silver Trust", category: "etfs" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury", category: "etfs" },
  { symbol: "HYG", name: "iShares High Yield Corp Bond", category: "etfs" },
  { symbol: "VWO", name: "Vanguard FTSE Emerging Mkts", category: "etfs" },
  { symbol: "SOXX", name: "iShares Semiconductor", category: "etfs" },
  { symbol: "SOXL", name: "Direxion Semiconductor 3x", category: "etfs" },
  { symbol: "TQQQ", name: "ProShares UltraPro QQQ 3x", category: "etfs" },
  { symbol: "SQQQ", name: "ProShares UltraPro Short QQQ", category: "etfs" },

  // ─── Forex (Yahoo Finance format) ───
  { symbol: "EURUSD=X", name: "Euro / US Dollar", category: "forex" },
  { symbol: "GBPUSD=X", name: "British Pound / US Dollar", category: "forex" },
  { symbol: "USDJPY=X", name: "US Dollar / Japanese Yen", category: "forex" },
  { symbol: "AUDUSD=X", name: "Australian Dollar / USD", category: "forex" },
  { symbol: "USDCAD=X", name: "US Dollar / Canadian Dollar", category: "forex" },
  { symbol: "USDCHF=X", name: "US Dollar / Swiss Franc", category: "forex" },
  { symbol: "NZDUSD=X", name: "New Zealand Dollar / USD", category: "forex" },
  { symbol: "EURGBP=X", name: "Euro / British Pound", category: "forex" },
  { symbol: "EURJPY=X", name: "Euro / Japanese Yen", category: "forex" },
  { symbol: "GBPJPY=X", name: "British Pound / Japanese Yen", category: "forex" },
  // ─── NSE Kenya ───
  { symbol: "SCOM", name: "Safaricom PLC", category: "nse" },
  { symbol: "SMER", name: "Sameer Africa PLC", category: "nse" },
  { symbol: "EQTY", name: "Equity Group Holdings", category: "nse" },
  { symbol: "KCB", name: "KCB Group PLC", category: "nse" },
  { symbol: "COOP", name: "Co-operative Bank", category: "nse" },
  { symbol: "ABSA", name: "Absa Bank Kenya", category: "nse" },
  { symbol: "EABL", name: "East African Breweries", category: "nse" },
  { symbol: "BAT", name: "BAT Kenya", category: "nse" },
  { symbol: "KPLC", name: "Kenya Power", category: "nse" },
  { symbol: "KQ", name: "Kenya Airways", category: "nse" },
  { symbol: "SCBK", name: "Standard Chartered Kenya", category: "nse" },
  { symbol: "NCBA", name: "NCBA Group", category: "nse" },
  { symbol: "BRIT", name: "Britam Holdings", category: "nse" },
  { symbol: "JUB", name: "Jubilee Holdings", category: "nse" },
  { symbol: "NMG", name: "Nation Media Group", category: "nse" },
  { symbol: "BAMB", name: "Bamburi Cement", category: "nse" },
  { symbol: "CTUM", name: "Centum Investment", category: "nse" },
  { symbol: "KEGN", name: "KenGen PLC", category: "nse" },
  { symbol: "DTK", name: "Diamond Trust Bank", category: "nse" },
  { symbol: "SASN", name: "Sasini PLC", category: "nse" },
];

// Category labels for UI
export const SYMBOL_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "stocks", label: "Stocks" },
  { id: "crypto", label: "Crypto" },
  { id: "futures", label: "Futures" },
  { id: "etfs", label: "ETFs" },
  { id: "forex", label: "Forex" },
  { id: "nse", label: "NSE Kenya" },
] as const;

export type SymbolCategory = typeof SYMBOL_CATEGORIES[number]["id"];
